const SERVICE_FEE=50; const RATE_PER_MILE=2.0; const PHONE='6625547497'; const EMAIL='chance_stanley@aol.com';
let selectedService='Parts'; let lastQuote='';
const $=id=>document.getElementById(id); const status=$('status');
document.querySelectorAll('.service').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.service').forEach(b=>b.classList.remove('active'));btn.classList.add('active');selectedService=btn.dataset.service;$('serviceBadge').textContent=selectedService;}));
$('quoteBtn').addEventListener('click',calculate); $('copyBtn').addEventListener('click',copyQuote); $('shareBtn').addEventListener('click',shareQuote); $('callBtn').addEventListener('click',()=>{location.href='tel:'+PHONE});
function money(n){return '$'+Number(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function showStatus(msg,isError=false){status.textContent=msg;status.className='status'+(isError?' error':'');status.style.display='block'} function hideStatus(){status.style.display='none'}
async function geocode(place){const q=place.includes(',')?place:place+', MS';const url='https://nominatim.openstreetmap.org/search?format=json&countrycodes=us&limit=1&q='+encodeURIComponent(q);const res=await fetch(url,{headers:{'Accept':'application/json'}});if(!res.ok)throw new Error('Could not reach location service.');const data=await res.json();if(!data.length)throw new Error('Could not find '+place+'. Try City, ST.');return {lat:data[0].lat,lon:data[0].lon,display:data[0].display_name};}
async function calculate(){const pickup=$('pickup').value.trim();const dropoff=$('dropoff').value.trim();$('result').style.display='none';hideStatus();if(!pickup||!dropoff){showStatus('Enter both pickup city and destination city.',true);return}showStatus('Calculating route...');try{const [a,b]=await Promise.all([geocode(pickup),geocode(dropoff)]);const routeUrl='https://router.project-osrm.org/route/v1/driving/'+a.lon+','+a.lat+';'+b.lon+','+b.lat+'?overview=false';const rr=await fetch(routeUrl);const route=await rr.json();if(!route.routes||!route.routes.length)throw new Error('No driving route found.');const miles=route.routes[0].distance/1609.344;const mileageCost=miles*RATE_PER_MILE;const total=Math.round(SERVICE_FEE+mileageCost);$('rPickup').textContent=pickup;$('rDropoff').textContent=dropoff;$('rMiles').textContent=miles.toFixed(1)+' mi';$('rFee').textContent=money(SERVICE_FEE);$('rMileageLabel').textContent='Mileage ('+miles.toFixed(1)+' mi × $'+RATE_PER_MILE.toFixed(2)+')';$('rMileage').textContent=money(mileageCost);$('rTotal').textContent=money(total);lastQuote=`WE GO - Dedicated Same-Day Courier\n\nService: ${selectedService}\nPickup: ${pickup}\nDestination: ${dropoff}\nLoaded Miles: ${miles.toFixed(1)}\nService Fee: ${money(SERVICE_FEE)}\nMileage: ${money(mileageCost)}\n\nTOTAL QUOTE: ${money(total)}\n\nWhen it can’t wait... WE GO.\n662-554-7497\n${EMAIL}`;$('result').style.display='block';hideStatus();$('result').scrollIntoView({behavior:'smooth',block:'nearest'});}catch(e){showStatus(e.message||'Something went wrong calculating the quote.',true)}}
async function copyQuote(){if(!lastQuote)return;await navigator.clipboard.writeText(lastQuote);alert('Quote copied.');}
async function shareQuote(){if(!lastQuote)return;if(navigator.share){await navigator.share({title:'WE GO Quote',text:lastQuote});}else{await copyQuote();}}
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));}
